# LLM-Based Code Repair & Fuzzing Experiment

This repository contains the orchestration scripts and tools for verifying, repairing, and fuzzing C and Rust programs generated by Large Language Models (LLMs). The pipeline identifies vulnerabilities (via AddressSanitizer), attempts to repair them using LLMs, and verifies the fixes using both static test fixtures and AFL++ fuzzing.

## 📋 Table of Contents

* Prerequisites
* Directory Structure
* Setup & Installation
* Usage
* 1. Automated Repair 
* 2. Rust Orchestration 
* 3. AFL Slicing 


* [Reproducibility Notes]

---

## 🛠 Prerequisites

Ensure the following tools are installed on your system:

* **Python 3.8+**
* **Clang / LLVM 14+** (Required for AddressSanitizer and fuzzing instrumentation)
* **AFL++** (American Fuzzy Lop Plus Plus)
* **Rust / Cargo** (If running `orchestrate_rust.py`)

### Python Dependencies

```bash
pip install openai google-genai anthropic tqdm

```

---

## 📂 Directory Structure

To ensure the experiment is reproducible, organize your files exactly as shown below. The scripts rely on specific relative paths for fixtures and logs.

```text
project_root/
├── scripts/
│   ├── orchestrate_repair.py    # (Renamed from orchestrate_final.py if needed)
│   ├── orchestrate_rust.py
│   └── afl_slice/               # Directory containing AFL slicing tools/scripts
├── study_verification/
│   ├── fixtures/                # Input files for test cases (e.g., checksum.in)
│   ├── run_gpt4o_temp02/        # Output from a previous generation run
│   │   ├── logs/
│   │   │   └── build_results.jsonl  # The log file containing failure data
│   │   └── gen/                 # Source code generated by the LLM
│   └── run_repaired/            # (Auto-created) Output dir for repairs
└── README.md

```

---

## 🚀 Usage

### 1. Automated Repair

The `orchestrate_repair.py` script reads a log of failed builds/runs, grabs the original source code, prompts an LLM to fix it, and verifies the fix.

**Environment Variables:**
You must set the API key for your chosen provider:

```bash
export OPENAI_API_KEY="sk-..."
# OR
export GEMINI_API_KEY="AIza..."
# OR
export ANTHROPIC_API_KEY="sk-ant..."

```

**Command:**

```bash
python3 scripts/orchestrate_repair.py \
    --run_dir ./study_verification/run_gpt4o_temp02 \
    --fixtures ./study_verification/fixtures \
    --provider openai \
    --model "gpt-4o" \
    --temperature 0.2 \
    --parallel 64

```

| Argument | Description |
| --- | --- |
| `--run_dir` | Directory containing the `logs/build_results.jsonl` file and source code. |
| `--fixtures` | Directory containing `.in` test files matching the problem slugs. |
| `--parallel` | Number of concurrent API requests/compilations (Default: 16). |

### 2. Rust Orchestration

Use `orchestrate_rust.py` to compile and verify Rust translations or generated Rust code. This script likely handles Cargo projects or `rustc` invocations directly.

**Command:**

```bash
python3 scripts/orchestrate_rust.py \
    --src_dir ./study_verification/rust_gen \
    --out_dir ./study_verification/rust_results \
    --fixtures ./study_verification/fixtures

```

*(Note: Adjust flags based on the specific arguments defined inside `orchestrate_rust.py`)*

### 3. AFL Slicing

The `afl_slice` tool is used to isolate relevant code segments for efficient fuzzing. If this is a Python script, run it as follows. If it is a binary, ensure it is in your `$PATH` or referenced relatively.

**Command:**

```bash
# Example if afl_slice is a Python script
python3 scripts/afl_slice/main.py \
    --target ./study_verification/run_repaired/B1_checksum_fixed.bin \
    --output_dir ./fuzz_results \
    --duration 60

```

**Command (If using AFL++ directly on the artifacts):**

```bash
afl-fuzz -i ./study_verification/fixtures -o ./fuzz_out -- ./your_compiled_binary @@

```

---

## 🔬 Reproducibility Notes

To replicate specific experimental runs:

1. **Lock your LLM Model:** Use specific model versions (e.g., `gpt-4o-2024-05-13`) instead of generic tags like `gpt-4o` to avoid drift.
2. **Temperature:** Always set `--temperature 0` or the exact value used (e.g., `0.2`) in the original run.
3. **Compiler Versions:** Ensure all machines use the same version of Clang (e.g., `clang-14`). Different sanitizer implementations can lead to different crash reports.
4. **Seeds:** If using AFL, set `AFL_NO_UI=1` and `AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1` (or equivalent) for consistent headless execution, though fuzzing is inherently stochastic.

### Troubleshooting

* **Permission Denied:** If you see `[Errno 13] Permission denied` on `.bin` files, the scripts have been patched to run `chmod +x`. Ensure your user has write access to the output directories.
* **Missing Fixtures:** Ensure fixture filenames match the slug format (e.g., `0021_checksum` expects `checksum.in`).
